name: Create release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    # container: electronuserland/builder:wine-mono

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js version
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      # ----------------------------------------#
      #                  Build                  #
      # ----------------------------------------#
      # - name: Install rpm need for electron builder
      #   run: brew install rpm
      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      # - name: Restore yarn cache
      #   uses: actions/cache@v3
      #   id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-
      # - name: Install dependencies
      #   run: |
      #     yarn install --frozen-lockfile
      # - name: Build Tints and Shades packages
      #   run: |
      #     ELECTRON_BUILDER_CACHE=$(pwd)/.cache/electron-builder WINEPREFIX=$(pwd)/.cache/.wine yarn package

      # ----------------------------------------#
      #                 Release                 #
      # ----------------------------------------#
      - name: Generate release body
        run: |
          yarn extract-latest-change-log
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          body_path: RELEASE_BODY.md

      # ----------------------------------------#
      #                 Uploads                 #
      # ----------------------------------------#
      # - name: Get package version
      #   id: get-package-version
      #   run: echo "PACKAGE_VERSION=${GITHUB_REF#v}" >> $GITHUB_OUTPUT
      # - name: Upload ia32 msi as release asset
      #   id: upload-release-asset-ia32-msi
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: ./build-packages/Tints and Shades ${{steps.get-package-version.outputs.PACKAGE_VERSION}} ia32.msi
      #     asset_name: Tints and Shades ${{steps.get-package-version.outputs.PACKAGE_VERSION}} ia32.msi
      # - name: Upload exe as release asset
      #   id: upload-release-asset-exe
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: ./build-packages/Tints and Shades ${{steps.get-package-version.outputs.PACKAGE_VERSION}}.exe
      #     asset_name: Tints and Shades ${{steps.get-package-version.outputs.PACKAGE_VERSION}}.exe
      # - name: Upload msi as release asset
      #   id: upload-release-asset-msi
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: ./build-packages/Tints and Shades ${{steps.get-package-version.outputs.PACKAGE_VERSION}}.msi
      #     asset_name: Tints and Shades ${{steps.get-package-version.outputs.PACKAGE_VERSION}}.msi
      # - name: Upload exe as release asset
      #   id: upload-release-asset-setup-exe
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: ./build-packages/Tints and Shades Setup ${{steps.get-package-version.outputs.PACKAGE_VERSION}}.exe
      #     asset_name: Tints and Shades Setup ${{steps.get-package-version.outputs.PACKAGE_VERSION}}.exe
      # - name: Upload exe blockmap as release asset
      #   id: upload-release-asset-setup-exe-blockmap
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: ./build-packages/Tints and Shades Setup ${{steps.get-package-version.outputs.PACKAGE_VERSION}}.exe.blockmap
      #     asset_name: Tints and Shades Setup ${{steps.get-package-version.outputs.PACKAGE_VERSION}}.exe.blockmap
      # - name: Upload i386 AppImage as release asset
      #   id: upload-release-asset-i386-AppImage
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: ./build-packages/Tints and Shades-${{steps.get-package-version.outputs.PACKAGE_VERSION}}-i386.AppImage
      #     asset_name: Tints and Shades-${{steps.get-package-version.outputs.PACKAGE_VERSION}}-i386.AppImage
      # - name: Upload mac zip as release asset
      #   id: upload-release-asset-mac-zip
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: ./build-packages/Tints and Shades-${{steps.get-package-version.outputs.PACKAGE_VERSION}}-mac.zip
      #     asset_name: Tints and Shades-${{steps.get-package-version.outputs.PACKAGE_VERSION}}-mac.zip
      # - name: Upload AppImage as release asset
      #   id: upload-release-asset-AppImage
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: ./build-packages/Tints and Shades-${{steps.get-package-version.outputs.PACKAGE_VERSION}}.AppImage
      #     asset_name: Tints and Shades-${{steps.get-package-version.outputs.PACKAGE_VERSION}}.AppImage
      # - name: Upload dmg as release asset
      #   id: upload-release-asset-dmg
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: ./build-packages/Tints and Shades-${{steps.get-package-version.outputs.PACKAGE_VERSION}}.dmg
      #     asset_name: Tints and Shades-${{steps.get-package-version.outputs.PACKAGE_VERSION}}.dmg
      # - name: Upload dmg blockmap as release asset
      #   id: upload-release-asset-dmg-blockmap
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: ./build-packages/Tints and Shades-${{steps.get-package-version.outputs.PACKAGE_VERSION}}.dmg.blockmap
      #     asset_name: Tints and Shades-${{steps.get-package-version.outputs.PACKAGE_VERSION}}.dmg.blockmap
      # - name: Upload amd64 deb as release asset
      #   id: upload-release-asset-amd64-deb
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: ./build-packages/tints-and-shades_${{steps.get-package-version.outputs.PACKAGE_VERSION}}_amd64.deb
      #     asset_name: tints-and-shades_${{steps.get-package-version.outputs.PACKAGE_VERSION}}_amd64.deb
      # - name: Upload i386 deb as release asset
      #   id: upload-release-asset-i386-deb
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: ./build-packages/tints-and-shades_${{steps.get-package-version.outputs.PACKAGE_VERSION}}_i386.deb
      #     asset_name: tints-and-shades_${{steps.get-package-version.outputs.PACKAGE_VERSION}}_i386.deb
      # - name: Upload i686 rpm as release asset
      #   id: upload-release-asset-i686-rpm
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: ./build-packages/tints-and-shades-${{steps.get-package-version.outputs.PACKAGE_VERSION}}.i686.rpm
      #     asset_name: tints-and-shades-${{steps.get-package-version.outputs.PACKAGE_VERSION}}.i686.rpm
      # - name: Upload x86_64 rpm as release asset
      #   id: upload-release-asset-x86_64-rpm
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create-release.outputs.upload_url }}
      #     asset_path: ./build-packages/tints-and-shades-${{steps.get-package-version.outputs.PACKAGE_VERSION}}.x86_64.rpm
      #     asset_name: tints-and-shades-${{steps.get-package-version.outputs.PACKAGE_VERSION}}.x86_64.rpm

